### ISSUE TITLE
README of @sunmao-ui/vite-plugins

### ISSUE THREAD

**Issue by FriedRiceNoodles** [smartxworks/sunmao-ui#562]
Need Readme.md of `@sunmao-ui/vite-plugins`
~~And what are `resolveId()` and `load()` use for?~~
I just read the document of rollup and vite, just forgive my stupid question plz...

**Comment by Yuyz0112** [comment]
Never mind!

BTW, the vite-plugins package is an internal package to serve examples in this repo. Maybe you want to use the vite-plugin-fs package which helps you sync schema to a file. A usage example of the fs plugin can be found in our starter template.
