### ISSUE TITLE
Feature: 支持 API 复制

### ISSUE THREAD

**Issue by ZhouAn0719** [smartxworks/sunmao-ui#571]
- 版本信息
    "@sunmao-ui/arco-lib": "^0.3.0",
    "@sunmao-ui/core": "0.7.3",
    "@sunmao-ui/echarts-lib": "^0.2.0",
    "@sunmao-ui/editor": "0.7.4",
    "@sunmao-ui/editor-sdk": "0.3.4",
    "@sunmao-ui/runtime": "0.7.3",
    "@sunmao-ui/shared": "^0.2.3",
    "@sunmao-ui/vite-plugin-fs": "^0.0.4-alpha.0",

- 需求描述
希望 sunmao 可以支持 API 的复制。
使用 sunmao 开发过程中，经常会有许多路径相似或者参数相似的 REST API。对于这些 API，希望可以和 UI 组件一样通过 Ctrl+C, Ctrl+V 实现快速复制。

**Comment by tanbowensg** [comment]
可以的。不过交互上可能不会用键盘，添加复制按钮更好一点。

**Comment by Yuyz0112** [comment]
> 经常会有许多路径相似或者参数相似的 REST API

off-topic: 之前一个和这个场景相关的 proposal https://github.com/smartxworks/sunmao-ui/issues/477
