### ISSUE TITLE
Improve: API 的 Event 编辑窗口尺寸略小

### ISSUE THREAD

**Issue by ZhouAn0719** [smartxworks/sunmao-ui#572]
- 版本信息
"@sunmao-ui/arco-lib": "^0.3.0",
"@sunmao-ui/core": "0.7.3",
"@sunmao-ui/echarts-lib": "^0.2.0",
"@sunmao-ui/editor": "0.7.4",
"@sunmao-ui/editor-sdk": "0.3.4",
"@sunmao-ui/runtime": "0.7.3",
"@sunmao-ui/shared": "^0.2.3",
"@sunmao-ui/vite-plugin-fs": "^0.0.4-alpha.0",

- 问题描述
当前的 API Event 编辑区域是以类似 ToolTip 的组件弹出的，编辑区域稍显拥挤。
如下图所示，Event 参数在弹窗中无法全部直接呈现出来，需要拖动滚动条查看。此外，js 表达式的输入框太小，不够直观。
![image](https://user-images.githubusercontent.com/78488205/184850088-942935b3-bba6-49e5-874b-ebb5e7aab2e7.png)

API 页面较为宽敞，例如截图中尚有许多空白区域，希望可以进行微调，以更方便的编辑 Event。

**Comment by tanbowensg** [comment]
了解，这里确实可以优化一下

**Comment by tanbowensg** [comment]
已经调整过，现在区域已经变大了
