### ISSUE TITLE
API body decoded error

### ISSUE THREAD

**Issue by WoeOm** [smartxworks/sunmao-ui#587]
**Version**
"editor": "0.7.4"
**Reproduction link**

**Steps to reproduce**
1. DataSource
2. set api Method to 'POST'
3. set BodyType to 'JSON'
4. body: {{{"test": 1}}}
<img width="714" alt="image" src="https://user-images.githubusercontent.com/7368203/187821772-d4ec8c09-9cdb-46c6-bc94-4421b152566c.png">

**What is expected?**
Correct json parsing parameters.

**What is actually happening?**

<img width="627" alt="image" src="https://user-images.githubusercontent.com/7368203/187821876-b2161e98-6cff-4916-8d86-4a3b04ac1ae7.png">

**Comment by WoeOm** [comment]
When method is `POST`, content-type should be set to `application/json`

<img width="406" alt="image" src="https://user-images.githubusercontent.com/7368203/187822646-6ea5a972-6cf9-4f1c-8e0d-8062a2662611.png">

**Comment by tanbowensg** [comment]
Good catch. Our `Fetch` data source is very basic for now. Everything need to be set be user manually.

In this case, user has to set `content-type` in `Headers` tab explicitly. 

We are looking for ways to improve the user experience of `Fetch`.
