### ISSUE TITLE
Rethinking lifecycle management with slot trait's ifCondition property

### ISSUE THREAD

**Issue by Yuyz0112** [smartxworks/sunmao-ui#590]
**Version**

0.8 alpha

**Background**

In the latest version, we designed the new slot trait with more powerful features like slot props and the ifCondition property.

But when a component has loop slots and an application puts several components into these slots, how the ifCondition works may surprise you.

For example:

```
component slots: slot_content[key=1], slot_content[key=2], slot_content[key=3] // <- you can think [key=n] is a slot props

application:
  put component_1 into slot_content, ifCondition is `$slot.key === 1`
  put component_2 into slot_content, ifCondition is `$slot.key === 2`
  put component_3 into slot_content, ifCondition is `$slot.key === 3`
```

Actually, there will be 3*3=9 renders for each slot element, and the result is

```
component_1 + slot_content[key=1] = render
component_1 + slot_content[key=2] = skip
component_1 + slot_content[key=3] = skip
component_2 + slot_content[key=1] = skip
component_2 + slot_content[key=2] = render
component_2 + slot_content[key=3] = skip
component_3 + slot_content[key=1] = skip
component_3 + slot_content[key=2] = skip
component_3 + slot_content[key=3] = render
```

**What is expected?**

It may be reasonable to optimize the render times of this scenario, but in the meantime, we should expect every slot element works fine and the performance does not suffer.

**What is actually happening?**

In the `UnmountImplWrapper`, we will teardown the component's state from the store when it's unmounted. Currently, we are using the unmount feature to implement slot trait's ifCondition feature too, this makes it extremely hard to design when to teardown the store.

**Comment by tanbowensg** [comment]
Seems like that there are 2 problems:
1. Render too many times when loop render slot.
2. The store is teared down in wrong time.

Is there a minimal example for the second problem?
